apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: custom-aws-s3-sink.kamelet.yaml
  annotations:
    camel.apache.org/kamelet.support.level: Stable
    camel.apache.org/catalog.version: 4.7.0-SNAPSHOT
    camel.apache.org/kamelet.icon: >-
      data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIGlkPSJMYXllcl8xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHg9IjAiIHk9IjAiIHZpZXdCb3g9IjAgMCAyNDguMiAzMDAiIHhtbDpzcGFjZT0icHJlc2VydmUiPjxzdHlsZT4uc3QyOHtmaWxsOiM4YzMxMjN9LnN0Mjl7ZmlsbDojZTA1MjQzfTwvc3R5bGU+PHBhdGggY2xhc3M9InN0MjgiIGQ9Ik0yMCA1Mi4xTDAgNjJ2MTc1LjVsMjAgOS45LjEtLjFWNTIuMmwtLjEtLjEiLz48cGF0aCBjbGFzcz0ic3QyOSIgZD0iTTEyNyAyMjJMMjAgMjQ3LjVWNTIuMUwxMjcgNzd2MTQ1Ii8+PHBhdGggY2xhc3M9InN0MjgiIGQ9Ik03OC43IDE4Mi4xbDQ1LjQgNS44LjMtLjcuMy03NC40LS41LS42LTQ1LjQgNS43LS4xIDY0LjIiLz48cGF0aCBjbGFzcz0ic3QyOCIgZD0iTTEyNC4xIDIyMi4zbDEwNC4xIDI1LjIuMi0uM1Y1Mi4xbC0uMi0uMi0xMDQuMSAyNS40djE0NSIvPjxwYXRoIGNsYXNzPSJzdDI5IiBkPSJNMTY5LjUgMTgyLjFsLTQ1LjQgNS44di03NS43bDQ1LjQgNS43djY0LjIiLz48cGF0aCBkPSJNMTY5LjUgODYuOWwtNDUuNCA4LjMtNDUuNC04LjNMMTI0IDc1bDQ1LjUgMTEuOSIgZmlsbD0iIzVlMWYxOCIvPjxwYXRoIGQ9Ik0xNjkuNSAyMTMuMWwtNDUuNC04LjMtNDUuNCA4LjMgNDUuMyAxMi43IDQ1LjUtMTIuNyIgZmlsbD0iI2YyYjBhOSIvPjxwYXRoIGNsYXNzPSJzdDI4IiBkPSJNNzguNyA4Ni45bDQ1LjQtMTEuMi40LS4xVi4zbC0uNC0uMy00NS40IDIyLjd2NjQuMiIvPjxwYXRoIGNsYXNzPSJzdDI5IiBkPSJNMTY5LjUgODYuOWwtNDUuNC0xMS4yVjBsNDUuNCAyMi43djY0LjIiLz48cGF0aCBjbGFzcz0ic3QyOCIgZD0iTTEyNC4xIDMwMGwtNDUuNC0yMi43di02NC4ybDQ1LjQgMTEuMi43LjgtLjIgNzMuNi0uNSAxLjMiLz48cGF0aCBjbGFzcz0ic3QyOSIgZD0iTTEyNC4xIDMwMGw0NS40LTIyLjd2LTY0LjJsLTQ1LjQgMTEuMlYzMDBNMjI4LjIgNTIuMWwyMCAxMHYxNzUuNWwtMjAgMTBWNTIuMSIvPjwvc3ZnPg==
    camel.apache.org/provider: Apache Software Foundation
    camel.apache.org/kamelet.group: AWS S3
    camel.apache.org/kamelet.namespace: karavan-1
  labels:
    camel.apache.org/kamelet.type: sink
spec:
  definition:
    title: Custom test S3 Sink
    description: >-
      Upload data to an Amazon S3 Bucket.


      The basic authentication method for the S3 service is to specify an access
      key and a secret key. These parameters are optional because the Kamelet
      provides a default credentials provider.


      If you use the default credentials provider, the S3 client loads the
      credentials through this provider and doesn't use the basic authentication
      method.


      In the header, you can optionally set the `file` / `ce-partition` property
      to specify the name of the file to upload.


      If you do not set the property in the header, the Kamelet uses the
      exchange ID for the file name.
    required:
      - bucketNameOrArn
      - region
    type: object
    properties:
      bucketNameOrArn:
        title: Bucket Name
        description: The S3 Bucket name or Amazon Resource Name (ARN).
        type: string
      accessKey:
        title: Access Key
        description: The access key obtained from AWS.
        type: string
        format: password
        xDescriptors:
          - urn:camel:group:credentials
      secretKey:
        title: Secret Key
        description: The secret key obtained from AWS.
        type: string
        format: password
        xDescriptors:
          - urn:camel:group:credentials
      region:
        title: AWS Region
        description: The AWS region to access.
        type: string
        enum:
          - ap-south-1
          - eu-south-1
          - us-gov-east-1
          - me-central-1
          - ca-central-1
          - eu-central-1
          - us-iso-west-1
          - us-west-1
          - us-west-2
          - af-south-1
          - eu-north-1
          - eu-west-3
          - eu-west-2
          - eu-west-1
          - ap-northeast-3
          - ap-northeast-2
          - ap-northeast-1
          - me-south-1
          - sa-east-1
          - ap-east-1
          - cn-north-1
          - us-gov-west-1
          - ap-southeast-1
          - ap-southeast-2
          - us-iso-east-1
          - ap-southeast-3
          - us-east-1
          - us-east-2
          - cn-northwest-1
          - us-isob-east-1
          - aws-global
          - aws-cn-global
          - aws-us-gov-global
          - aws-iso-global
          - aws-iso-b-global
      autoCreateBucket:
        title: Autocreate Bucket
        description: Specifies to automatically create the S3 bucket.
        type: boolean
        default: false
      useDefaultCredentialsProvider:
        title: Default Credentials Provider
        description: >-
          If true, the S3 client loads credentials through a default credentials
          provider. If false, it uses the basic authentication method (access
          key and secret key).
        type: boolean
        default: false
      uriEndpointOverride:
        title: Overwrite Endpoint URI
        description: >-
          The overriding endpoint URI. To use this option, you must also select
          the `overrideEndpoint` option.
        type: string
      overrideEndpoint:
        title: Endpoint Overwrite
        description: >-
          Select this option to override the endpoint URI. To use this option,
          you must also provide a URI for the `uriEndpointOverride` option.
        type: boolean
        default: false
      forcePathStyle:
        title: Force Path Style
        description: Forces path style when accessing AWS S3 buckets.
        type: boolean
        default: false
      batchSize:
        title: Batch size
        description: The batch size (in bytes) in streaming upload mode.
        type: int
        default: 1000000
      batchMessageNumber:
        title: Batch message number
        description: The number of messages composing a batch in streaming upload mode.
        type: int
        default: 10
      fileFormat:
        title: content type of file
        description: test content type
        type: string
        enum:
          - text
          - parquet
          - json
      avroSchema:
        type: string
        title: Avro Schema
        description: The Avro schema used for conversion.
  dependencies:
    - camel:core
    - camel:aws2-s3
    - camel:kamelet
    - camel:jackson
  template:
    route:
      id: route-73f9
      from:
        id: from-1e91
        uri: kamelet:source
        steps:
          - choice:
              id: choice-a5021
              when:
                - id: when-58a9
                  expression:
                    simple:
                      id: simple-91b0
                      expression: "'{{fileFormat}}' == 'json'"
                  steps:
                    - marshal:
                        id: marshal-f794
                        json:
                          id: json-892f
                          library: Jackson
                    - setHeaders:
                        id: setHeaders-55e5
                        headers:
                          - id: setHeader-d683
                            name: CamelAwsS3Key
                            expression:
                              simple:
                                id: simple-9f52
                                expression: >-
                                  camel_data_format/json/${date:now:yyyy}/${date:now:MM}/${date:now:dd}/file-${date:now:yyyyMMddHHmmssSSS}.json
                          - id: setHeader-aa3c
                            name: CamelAwsS3ContentType
                            expression:
                              simple:
                                id: simple-54a9
                                expression: application/json
                - id: when-0ef0
                  expression:
                    simple:
                      id: simple-4885
                      expression: "'{{fileFormat}}' == 'text'"
                  steps:
                    - setHeaders:
                        id: setHeaders-b1f4
                        headers:
                          - id: setHeader-d374
                            name: CamelAwsS3Key
                            expression:
                              simple:
                                id: simple-06fb
                                expression: >-
                                  camel_data_format/text/${date:now:yyyy}/${date:now:MM}/${date:now:dd}/file-${date:now:yyyyMMddHHmmssSSS}.text
                          - id: setHeader-6c2f
                            name: CamelAwsS3ContentType
                            expression:
                              simple:
                                id: simple-48dd
                                expression: text/plain
                - id: when-3a89
                  expression:
                    simple:
                      id: simple-018a
                      expression: "'{{fileFormat}}' == 'parquet'"
                  steps:
                    - setHeaders:
                        id: setHeaders-c090
                        headers:
                          - id: setHeader-4dfe
                            name: CamelAwsS3Key
                            expression:
                              simple:
                                id: simple-1587
                                expression: >-
                                  camel_data_format/parquet/${date:now:yyyy}/${date:now:MM}/${date:now:dd}/file-${date:now:yyyyMMddHHmmssSSS}.parquet
                          - id: setHeader-c326
                            name: CamelAwsS3ContentType
                            expression:
                              simple:
                                id: simple-61dc
                                expression: application/vnd.apache.parquet
                          - id: setHeader-693f
                            name: Content-Type
                            expression:
                              constant:
                                id: constant-4995
                                expression: application/vnd.apache.parquet
              otherwise:
                id: otherwise-b58d
                steps:
                  - setHeader:
                      id: setHeader-92ab
                      name: CamelAwsS3Key
                      expression:
                        simple:
                          id: simple-bb34
                          expression: failed.txt
          - to:
              id: to-fc19
              uri: aws2-s3
              parameters:
                secretKey: "{{?secretKey}}"
                accessKey: "{{?accessKey}}"
                region: "{{region}}"
                autoCreateBucket: "{{autoCreateBucket}}"
                useDefaultCredentialsProvider: "{{useDefaultCredentialsProvider}}"
                uriEndpointOverride: "{{?uriEndpointOverride}}"
                overrideEndpoint: "{{overrideEndpoint}}"
                forcePathStyle: "{{forcePathStyle}}"
                batchSize: "{{batchSize}}"
                batchMessageNumber: "{{batchMessageNumber}}"
                keyName: "{{?keyName}}"
                bucketNameOrArn: s2-s3:{{bucketNameOrArn}}
