
name: Webhook POST Logger

on:
  workflow_dispatch:
    inputs:
      payload:
        description: "POST request payload"
        required: true
        default: "{}"

jobs:
  log_payload:
    runs-on: ubuntu-latest
    steps:
    - name: Print POST payload
      run: |
        echo "Payload: ${{ github.event.inputs.payload }}"
